### PR TITLE
New resize/optimize engine - Sharp

### PR DESCRIPTION
**Pull request by jimmynicol**
Anyone interested in testing this PR out, it is basically an exploration in using [sharp](https://github.com/lovell/sharp) as the engine for both resizing and optimizing the images. This is in place of [gm](https://github.com/aheckmann/gm) and in the brief tests I have tried I am seeing around 4-5 times speed improvement.

Furthermore the repo is now able to run on cedar-14 stack on Heroku (see #28).

So if anyone is able I would love to have some more eyes on this, but I think it is definately the right way to move forward. It will also allow the repo to ditch imagemin which is flaky in deployments to Heroku and slow, although i have upgraded to the most recent version which looks like an improvement.

### CODE REVIEW

**Comment by jimmynicol** [comment]
I should have mentioned to test this out, you will need to checkout the repo, link it globally and then run the new command with the engine flag set to `sharp`. See [this commit](https://github.com/jimmynicol/image-resizer/blob/sharp/bin/image_resizer.js#L129) for more information.

**Comment by joonhocho** [comment]
+1

**Comment by jgillman** [comment]
A new install notes for any newbs like myself :sweat_smile: 

Install sharp for your OS: https://github.com/lovell/sharp#installation

```sh
# Uninstall image-resizer
npm uninstall -g image-resizer

# Install the sharp branch of image-resizer
npm install -g git://github.com/jimmynicol/image-resizer#sharp
```

**Comment by jgillman** [comment]
I've just been setting this up locally to test out and get the following error output: https://gist.github.com/jgillman/72b68040b492ceb25fc6

**Comment by jimmynicol** [comment]
Oops my bad... I forgot to change the dependency link for `image-resizer` in the generated file to point to the git branch. I just pushed out that change as an update to the PR but you can fix it manually in your local install by changing your package.json to:

`"image-resizer": "git://github.com/jimmynicol/image-resizer.git#sharp",`

Let me know if you see anything else you are having issues with. Thanks so much for giving this a test drive I really appreciate it.

**Comment by jgillman** [comment]
@jimmynicol Nice! Thanks for the fast turn around. Sharp is looking like it's gonna be the way to go. Especially with the whole Heroku bug holding back IM and GM.

Just testing locally in a clean project folder and sharp is doing all the resizing now. I'm experiencing two bugs which I'll outline here, but I can create issues for them if you'd like to handle it that way.

First issue is that if I try to get the original nothing seems to happen and the request appears to hang. I'm hitting `http://localhost:3003/test.png`. When I stop the page load in the browser node outputs:

```
GET /test.png - - ms - -
```

Second issue: Just a `request/response` switcheroo [from the last commit](https://github.com/jimmynicol/image-resizer/commit/2bfb2c8cd462812aa1a6027c57bd568b0b8c876e). 500s all requests to `/favicon.ico`.

**Comment by jimmynicol** [comment]
@jgillman,

Feel free to create some issues so I can track them. The favicon one is my bad, I should really be using the errorHandler middleware for this instead of the poor kluge I have in there now.

I will dig into the original image one though that seems like an important one.

Thanks again for your help.

PS: your portfolio site is nice!

**Comment by jgillman** [comment]
Last bit of productivity tonight: Tested on Heroku with a `cedar-14` and it works like a charm (after fixing the favicon thing) http://intense-hollows-9218.herokuapp.com/s100/test.jpg

I also tested on a deprecated `cedar` stack by accident and that did not go so well. But it's deprecated, so who cares!

Again, thank you for the big chunk of work here. Hoping to get this integrated into our production app this week!

**Comment by jimmynicol** [comment]
I should have time to dig into this tomorrow evening so I will try and get this PR merged into master so you can live off the NPM version instead of git branches.

**Comment by jgillman** [comment]
:+1:

**Comment by jimmynicol** [comment]
A bunch of updates have been pushed to this branch. Specifically fixing:

 - https://github.com/jimmynicol/image-resizer/issues/36
 - https://github.com/jimmynicol/image-resizer/issues/37

Also I have added a bunch of logic to warn the user that the `vips` dependency is not met, something that seems to be a recurring theme with users not installing the image library.

You can also, at least for now, see a side by side comparison of `sharp` vs `gm`. To see this run the repo locally (ie not using the app generator) and head to `/test-page2`. It shows pretty clearly how much faster sharp is and I spent some time tweaking the settings so the images were of a comparable quality.

In a few days I will push out this PR and completely remove both `gm` and `imagemin` from the codebase. This will affect the sepia filter and also how much metadata is returned via an identify call but I think these are small prices to pay for the speed and ability to run on the latest Heroku stacks.

**Comment by jgillman** [comment]
Just upgraded and did some testing, #36 is totally fixed and pulling/optimizing the original works really well. #37 isn't fixed, but I left a comment there.

Also deployed to my Heroku instance and verified that everything looks a-okay up there, too!

**Comment by jimmynicol** [comment]
Oops, copied the code over from `test.js` poorly. The favicon issue should be fixed now.

**Comment by jgillman** [comment]
Beautiful! This is working super well now. :shipit:

Would it make sense to merge this in as-is and remove the `gm` and `imagemin` dependencies in a separate PR?

**Pull request merged**
